name=M5Unit-TOF
version=0.2.1
author=M5Stack
maintainer=M5Stack
sentence=Library for M5Stack UNIT TOF using M5UnitUnified
paragraph=Supports VL53L0X (UnitToF SKU:U010, HatToF SKU:U072, UnitToF90 SKU:U196) and VL53L1X (UnitToF4M SKU:U172) Time-of-Flight ranging sensors.
category=Device Control
url=https://github.com/m5stack/M5Unit-TOF
architectures=esp32
includes=M5UnitUnifiedTOF.h
depends=M5UnitUnified,M5Utility,M5HAL
